apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rekor-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rekor-server
    app.kubernetes.io/part-of: rekor
  name: rekor-server
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rekor-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rekor-server
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/rekor/rekor-server@sha256:133e42c7dd44ce6d12a3cee28ead1a4eb1a99ebaaa07d67d4362eec7561ae672
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
status: {}
