apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rekor-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rekor-server
    app.kubernetes.io/part-of: rekor
  name: rekor-server
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rekor-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rekor-server
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/rekor/rekor-server@sha256:e5572d2a9de0226791c0e1c0d1bc47fe7c0a3e4bd984cea423f6df7879224405
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
status: {}
