apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: backfill-redis
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/rekor/backfill-redis@sha256:aac9c4d61cec2233108235192fe5812ece7a6cd7dcad41dcdcc025faf32d4c06
        name: container-image
        resources: {}
status: {}
