apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: backfill-redis
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/rekor/backfill-redis@sha256:e9cfb7c396a0f08cde33b6d032998a86f46d62aa4077c72411eaa282e1b13e08
        name: container-image
        resources: {}
status: {}
