apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: backfill-redis
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backfill-redis
    app.kubernetes.io/part-of: rekor
  name: backfill-redis
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: backfill-redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: backfill-redis
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/rekor/backfill-redis@sha256:411606d050cf8b3c4f71909c4ebf2bcb3177460e4abc348fc779d41c687b111d
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
status: {}
