apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: backfill-redis
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backfill-redis
    app.kubernetes.io/part-of: rekor
  name: backfill-redis
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: backfill-redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: backfill-redis
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/rekor/backfill-redis@sha256:d402ca8667d3ccc8d439ecdfc56cf90f35d8f2de97af3d7147943304c22648a0
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
status: {}
