apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rekor-server
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/rekor/rekor-server@sha256:51423171b15089d2e378bc6f5886e8f46859c736db33c146ae026484a2865b3a
        name: container-image
        resources: {}
status: {}
